### ISSUE TITLE
[mobile] bugs

### ISSUE THREAD

**Issue by alexdefender** [zonzujiro/kottans_website#11]
1. [one](https://drive.google.com/file/d/1Gb4u2CFywnRtt7xOuZQeleMUhdHNoqYQ/view?usp=sharing) - arrow disappears
2. [two](https://drive.google.com/open?id=1hpjDgoce14QvWz0R3FD1cGlPPCHm0MQh) - buttons do not work and the number does not change
3. [three](https://drive.google.com/open?id=17I9bRdgIpFl0rfZzwJZkF8CklQ2WCEuq)

**Comment by A-Ostrovnyy** [comment]
Can you provide us with access to the third image?

**Comment by alexdefender** [comment]
Done

**Comment by A-Ostrovnyy** [comment]
Thanks)
1 - Fixed
3 - Fixed

**Comment by zonzujiro** [comment]
@A-Ostrovnyy can we close this one?

**Comment by A-Ostrovnyy** [comment]
@zonzujiro need to fix 2-nd point. Please reopen issue.
