### ISSUE TITLE
[mobile] "Read more" button does not disappear

### ISSUE THREAD

**Issue by turchak** [zonzujiro/kottans_website#12]
In the section "About Kottans", after press button "READ MORE" its expand but the button still exists with the text "READ MORE"

---
👆Before click
<img src="https://user-images.githubusercontent.com/17525239/71541971-0f1bb380-2969-11ea-911a-bc7b611b5e72.png" width="250">

---
👇After click
<img src="https://user-images.githubusercontent.com/17525239/71541972-0f1bb380-2969-11ea-9f6a-b6dad7d3cf5e.png" width="250">

**Comment by zonzujiro** [comment]
Looks like according to design.
