### ISSUE TITLE
Duplicate meta tag

### ISSUE THREAD

**Issue by turchak** [zonzujiro/kottans_website#13]
`<meta name="theme-color" content="#fff" /> ` - doubled
https://github.com/zonzujiro/kottans_website/blob/f81b85ed78925bdfaab24237a2d469fda29fd0c7/build/index.html#L8-L12

**Comment by zonzujiro** [comment]
Looks like a great thing for PR :D

**Comment by A-Ostrovnyy** [comment]
Fixed
