### ISSUE TITLE
Animations

### ISSUE THREAD

**Issue by Zihfred** [zonzujiro/kottans_website#4]
1. When I click on menu items, momentarily screen changing, I think you need to add animation for 
2. I don't see the "Up to Top" button

**Comment by A-Ostrovnyy** [comment]
Thanks for the issue.
1. fixed in [PR](https://github.com/zonzujiro/kottans_website/pull/10)
2. we don't have "Scroll to top" button on design.

**Comment by zonzujiro** [comment]
Don't think that we need a button "To top". Site not so large.
