### ISSUE TITLE
[desktop] Scroll bar doesn't appear

### ISSUE THREAD

**Issue by turchak** [zonzujiro/kottans_website#5]

**Comment by zonzujiro** [comment]
Pls provide description.
Would be great if it will be with screenshot or smth

**Comment by turchak** [comment]
There is no scroll bar at the right rise, but site able to scroll
Tested on Ubuntu 18.04 and Windows 10 (chrome browser)
![Screenshot_826](https://user-images.githubusercontent.com/17525239/71527045-43985c80-28e2-11ea-9454-42be70bce6ba.png)

**Comment by A-Ostrovnyy** [comment]
Fixed

**Comment by zonzujiro** [comment]
Great work, guys. Thx!
