### ISSUE TITLE
[mobile] menu does not work propperly

### ISSUE THREAD

**Issue by boxdxnx** [zonzujiro/kottans_website#6]
## "hamburger" works only at the top of the page 

![hamburger](https://i.imgur.com/Cuc6JcA.png)

maybe it is the same issue as [this](https://github.com/zonzujiro/kottans_website/issues/1)

**Comment by A-Ostrovnyy** [comment]
Fixed

**Comment by boxdxnx** [comment]
@A-Ostrovnyy 👍🏻

**Comment by alexdefender** [comment]
Mobile menu is not correct 
Android 9, Chrome 79
https://drive.google.com/file/d/14-AxYPg0QHxIJyjxnqY2aE9q4t0dvjo4/view?usp=sharing

**Comment by A-Ostrovnyy** [comment]
@alexdefender it's fixed but not deployed yet.
[Video](https://share.vidyard.com/watch/WjJgzMihw5WcWo6Xewegtg?)

**Comment by A-Ostrovnyy** [comment]
@alexdefender it's fixed but not deployed yet.
[Video](https://share.vidyard.com/watch/WjJgzMihw5WcWo6Xewegtg?)
