### ISSUE TITLE
Problem with z-index on hamburger icon 

### ISSUE THREAD

**Issue by xsorter** [zonzujiro/kottans_website#8]
It seems is have some z-index issues
![issue](https://user-images.githubusercontent.com/17088715/71527782-83147800-28e5-11ea-94af-f0328ba83428.jpg)

Steps to reproduce:
1. Open main page
2. Change resolution width to 360px
3. Scroll down to slider

**Comment by A-Ostrovnyy** [comment]
Thanks for the issue.
Fixed.
