### ISSUE TITLE
Small bugs

### ISSUE THREAD

**Issue by nazmariam** [zonzujiro/kottans_website#9]
1.  It seems like [this](https://prnt.sc/qgj88n) border should be at the bottom of the string
2. There is a problem with burger navigation on mobile:  [video](https://drive.google.com/open?id=1G2URcCPxO-vrv8zM6N_ALFGOxuWTbRKK) 
3. Mb it is better to put real sharable links (using social networks API) [here](https://prnt.sc/qgjdiv) ?
4. Please fix typo [here](https://prnt.sc/qgjfyu)

**Comment by A-Ostrovnyy** [comment]
1. Fixed
2. Fixed. Better use online tools for sharing video like [Loom](https://www.loom.com/) or [Vidyard](https://www.vidyard.com/)
3. Need texts and images for those links.
4. Fixed
